using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CycleProvider.Contracts
{
    /// <summary>
    /// Odpowiedź dlaczego - Contract for base definition of person
    /// </summary>
    public interface IPerson
    {
        /// <summary>
        /// Autogenerated number incremented by 1
        /// </summary>
        int Id { get; }
        /// <summary>
        /// First Name of person
        /// </summary>
        /// <exception cref="HRException">First name must be single word without alfanumerical only</exception>
        string FirstName { get; set; }
        string LastName { get; set; }
        DateTime BirthDate { get; set; }
    }
}
